### ISSUE TITLE
IndexOutOfRangeException: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterApps/People#146]
### Steps to reproduce
No idea how to do that, its random. 

### Expected result
The person page should open

### Actual result
I see the following exception (which is in Technical information)

### Technical information
When i go to `/people/persons/{?}`. Sometimes the following exception occurs, most of the times it doesn't.
```
"System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Starcounter.Query.Execution.CodeGenFilterCacheShared.CreateFilter(CodeGenFilterInstrArray instrArray, DbTypeCode[] varTypes, UInt32 maxStackSize, UInt32 dataCount, RowTypeBinding typeBinding, Int32 extentNumber) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter\Query\Execution\CodeGeneration\CodeGenFilterCache.cs:line 202
   at Starcounter.Query.Execution.CodeGenFilterPrivate.GetFilterHandle() in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter\Query\Execution\CodeGeneration\CodeGenFilterPrivate.cs:line 215
   at Starcounter.Query.Execution.FullTableScan.CreateEnumeratorWithNativeFilter() in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter\Query\Execution\Enumerators\FullTableScan.cs:line 293
   at Starcounter.Query.Execution.FullTableScan.MoveNext() in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter\Query\Execution\Enumerators\FullTableScan.cs:line 411
   at People.PersonPage.RefreshCustomContactInfos() in C:\adfenix-codebase\People\src\People\ViewModels\PersonPage.json.cs:line 228
   at People.PersonPage.RefreshPerson(String ID) in C:\adfenix-codebase\People\src\People\ViewModels\PersonPage.json.cs:line 171
   at People.PartialHandlers.<>c__DisplayClass0_1.<Register>b__10() in C:\adfenix-codebase\People\src\People\Api\PartialHandlers.cs:line 119
   at Starcounter.Db.<>c__DisplayClass50_0`1.<Scope>b__0() in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter\Db.cs:line 531
   at Starcounter.Db.Scope(Action action, Boolean isReadOnly) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter\Db.cs:line 507
   at Starcounter.Db.Scope[TResult](Func`1 func, Boolean isReadOnly) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter\Db.cs:line 532
   at People.PartialHandlers.<>c.<Register>b__0_9(String id) in C:\adfenix-codebase\People\src\People\Api\PartialHandlers.cs:line 112
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 210
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1236
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter.Internal\Rest\Self.cs:line 390
   at Starcounter.Self.GET[T](String uri, HandlerOptions ho) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter.Internal\Rest\Self.cs:line 22
   at People.MainHandlers.<>c__DisplayClass6_0.<GetLauncherPage>b__0() in C:\adfenix-codebase\People\src\People\Api\MainHandlers.cs:line 159
   at Starcounter.Db.<>c__DisplayClass50_0`1.<Scope>b__0() in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter\Db.cs:line 531
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter\TransactionManager.cs:line 551
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter\Transaction.cs:line 224
   at Starcounter.Db.Scope(Action action, Boolean isReadOnly) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter\Db.cs:line 505
   at Starcounter.Db.Scope[TResult](Func`1 func, Boolean isReadOnly) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter\Db.cs:line 532
   at People.MainHandlers.GetLauncherPage(String url, Boolean dbScope) in C:\adfenix-codebase\People\src\People\Api\MainHandlers.cs:line 159
   at People.MainHandlers.<Register>b__5_7(String id) in C:\adfenix-codebase\People\src\People\Api\MainHandlers.cs:line 78
   at People.AuthorizedHandle.<>c__DisplayClass1_1`1.<GET>b__1() in C:\adfenix-codebase\People\src\People\Helpers\AuthorizedHandle.cs:line 21
   at People.AuthorizedHandle.TrySignIn(String getUrl, String param, Func`1 code) in C:\adfenix-codebase\People\src\People\Helpers\AuthorizedHandle.cs:line 29
   at People.AuthorizedHandle.<>c__DisplayClass1_0`1.<GET>b__0(T param) in C:\adfenix-codebase\People\src\People\Helpers\AuthorizedHandle.cs:line 21
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 210
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9432\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 350
HResult=-2146233080
"
```

##### Starcounter version 
2.3.1.7454

##### Involved apps' version
![image](https://user-images.githubusercontent.com/4388707/31711180-a1464408-b3f7-11e7-8d65-2930e989ee8d.png)

**Comment by bouguila** [comment]
closing as not possible to reproduce.
