### ISSUE TITLE
Changing CustomContactFields Name causes error

### ISSUE THREAD

**Issue by Joltrix** [StarcounterApps/People#66]
### Steps to reproduce
Go to Edit a person, and then click to add a custom field (if there are none already). After a custom field have been created, change its name, and then click on save.

### Expected result
It should save the new value, and delete the old value (since it deletes any values that are not currently being used by any user)

Like it does in inside.starcounter.com. There it works fine

### Actual result
It results in errors, but the change is made. So once you refresh the browser, the old "name"/property have been deleted, and the new one is displayed like it's supposed to

### Technical information
Starcounter Log:

```
System.Exception: ScErrDataBindingForJsonException (SCERR14012): An exception occurred when a databinding for a property in json was used. Property 'Name' in 'StandalonePage.PersonPage.CustomContactInfos.CustomContactInfoRelationPage.CustomContactInfoRelationTypes.CustomContactInfoRelationTypesElementJson'.
Version: 2.3.0.5619.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14012.
   at lambda_method(Closure , Json )
   at Starcounter.Templates.Property`1.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 202
   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 347
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 245
   at Starcounter.Json.<>c__DisplayClass119_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 209
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter\TransactionManager.cs:line 471
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.Json.CollectChangesForArray(Json arr, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 307
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 254
   at Starcounter.Json.<>c__DisplayClass119_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 209
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter\TransactionManager.cs:line 471
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 345
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 245
   at Starcounter.Json.<>c__DisplayClass119_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 209
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter\TransactionManager.cs:line 471
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.Json.CollectChangesForArray(Json arr, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 307
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 254
   at Starcounter.Json.<>c__DisplayClass119_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 209
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter\TransactionManager.cs:line 471
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 345
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 245
   at Starcounter.Json.<>c__DisplayClass119_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 209
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter\TransactionManager.cs:line 471
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 345
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 245
   at Starcounter.Json.<>c__DisplayClass119_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 209
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 70
   at Starcounter.Json.<>c__DisplayClass119_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 217
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 70
   at Starcounter.Json.CollectChangesForArray(Json arr, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 307
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 254
   at Starcounter.Json.<>c__DisplayClass119_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 209
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 70
   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 345
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 245
   at Starcounter.Json.<>c__DisplayClass119_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 209
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 70
   at Starcounter.XSON.ChangeLog.Generate(Boolean flushLog, Change[]& changeArr) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\ChangeLog.cs:line 97
   at Starcounter.XSON.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 117
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 65
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 796
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR14012
---> Starcounter.DbException: ScErrInvalidObjectAccess (SCERR4174): The operation failed because of an invalid object access.
Version: 2.3.0.5619.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4174.
   at Starcounter.Internal.DbState.ReadString(UInt64 oid, UInt64 address, Int32 index) in C:\TeamCity\BuildAgent\work\sc-2004\Level1\src\Starcounter\Internal\DbState.cs:line 683
   at lambda_method(Closure , Json )
ErrorCode=4174
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4174
```

Console Log:

![image](https://cloud.githubusercontent.com/assets/10708580/22435489/896ed376-e720-11e6-8cd7-f89942456d8c.png)

##### Starcounter version
Starcounter RC-2.3.0.5619

##### Involved apps' version
StarcounterSamples/People@1.0.0.0
StarcounterPrefabs/Images@1.0.0.0
StarcounterPrefabs/Launcher@5.0.1
StarcounterPrefabs/SignIn@5.0.5

 
##### Browsers affected

(Only tried in Chrome)

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Screenshot

![peopleerror](https://cloud.githubusercontent.com/assets/10708580/22435734/77b003b6-e721-11e6-99af-76884eb06e85.gif)

**Comment by warpech** [comment]
@un-tone any ideas here?

**Comment by un-tone** [comment]
Was fixed with https://github.com/StarcounterApps/People/pull/81/commits/01f171c58ba2fa658b217abb180d39a017989d0f.
Closing as resolved.
