### ISSUE TITLE
Creating a new Person when there are no custom fields causes error

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/People#80]
### Steps to reproduce

1. Start Launcher, SignIn, People (all develop branch) on an empty database
2. Go to `localhost:8080/signin/generateadminuser` to generate the admin user
3. Go to `localhost:8080/launcher` and sign in as `admin/admin`
4. Click on "Persons" in the left menu
5. Click on "Add person"
6. Type in the first name
7. Press "Save"

### Expected result

Should create a new person

### Actual result

Throws an exception:

```
System.Exception: ScErrDataBindingForJsonException (SCERR14012): An exception occurred when a databinding for a property in json was used. Property 'Name' in 'StandalonePage.PersonPage.CustomContactInfoRelationTypes.CustomContactInfoRelationTypesElementJson'.
Version: 2.3.0.6120.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14012.
   at lambda_method(Closure , Json )
   at Starcounter.Templates.Property`1.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 214
   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 345
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 243
   at Starcounter.Json.<>c__DisplayClass119_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 207
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter\Transaction.cs:line 216
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 66
   at Starcounter.Json.CollectChangesForArray(Json arr, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 305
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 252
   at Starcounter.Json.<>c__DisplayClass119_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 207
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter\Transaction.cs:line 216
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 66
   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 343
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 243
   at Starcounter.Json.<>c__DisplayClass119_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 207
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter\Transaction.cs:line 216
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 66
   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 343
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 243
   at Starcounter.Json.<>c__DisplayClass119_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 207
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter\TransactionManager.cs:line 551
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter\Transaction.cs:line 224
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 66
   at Starcounter.Json.<>c__DisplayClass119_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 215
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.Json.CollectChangesForArray(Json arr, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 305
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 252
   at Starcounter.Json.<>c__DisplayClass119_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 207
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 343
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 243
   at Starcounter.Json.<>c__DisplayClass119_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 207
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.XSON.ChangeLog.Generate(Boolean flushLog, Change[]& changeArr) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\ChangeLog.cs:line 97
   at Starcounter.XSON.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 117
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 68
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 796
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR14012
---> Starcounter.DbException: ScErrInvalidObjectAccess (SCERR4174): The operation failed because of an invalid object access.
Version: 2.3.0.6120.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4174.
   at Starcounter.Internal.DbState.ReadString(UInt64 oid, UInt64 address, Int32 index) in C:\TeamCity\BuildAgent\work\sc-4133\Level1\src\Starcounter\Internal\DbState.cs:line 683
   at lambda_method(Closure , Json )
ErrorCode=4174
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4174
```

##### Browsers affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Screenshot

![2017-03-28 23_21_15-people](https://cloud.githubusercontent.com/assets/566463/24428006/43ba6d1c-140d-11e7-80a8-981b28b3c481.png)

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterApps/People/pull/81

**Comment by un-tone** [comment]
Closing as done.
